### ISSUE TITLE
Integrate Outlooks' annotation modifiers convention

### ISSUE THREAD

**Issue by cy255** [microsoft/swift-guide#18]
# Convention

# Rationale

# Example

**Comment by cy255** [comment]
Closing the issue as most of the annotation modifiers convention is quite straightforward and well documented on the official guideline: https://docs.swift.org/swift-book/ReferenceManual/Attributes.html

@dalemyers FYI.

**Comment by dalemyers** [comment]
Yeah, makes sense. Originally this order wasn't specified, but then tools like SwiftLint came along and gave us a standard order which we adopted.
