### ISSUE TITLE
Integrating the Outlook style guide

### ISSUE THREAD

**Issue by dalemyers** [microsoft/swift-guide#5]
In Outlook for iOS, we have our own style guide for Swift which is much more fully fledged than this style guide. I believe we also have more lines of Swift than anyone else at Microsoft, and have already shared our style guide with numerous other teams. Based on that, I think it would be a massive win for Swift programmers at Microsoft (and anyone else using this style guide) to merge our one into here.

The problem is that our style guide doesn't follow the layout of this one and it would be quite an undertaking as far as I can tell to integrate it. This is what we have for now: https://msiosdocs.azurewebsites.net/source_code/style_guide/swift/

How can we effectively integrate the two style guides? 

Edit: This isn't a `new convention` but there wasn't a "general issue" button.

**Comment by cy255** [comment]
Hi Dale,
Thanks for sharing the Outlook Swift guide! The swift-guide repo is an open-source repo aiming to benefit as many Swift engineers as possible so any contributions are welcome. The swift-guide conventions are written in Markdown for best integration with GitHub Pages. The integration process is to pick an area / areas not covered by swift-guide, file an issue correspondingly and make a pull-request following [contributing guideline](https://microsoft.github.io/swift-guide/CONTRIBUTING.html). The integration could be done over multiple PRs as well. Re-structuring existing guidelines to match the swift-guide conventions does take some time and effort but it's a worthy process and it will benefit engineers within and outside Microsoft; I'm happy to share the load.
Side note: swift-guide was designed to not offer any guidance on formatting. All formatting in the example code follows the Swift.org formatting.

**Comment by dalemyers** [comment]
Cool. Just wanted to make sure you wouldn't be overwhelmed if I open a large PR with this stuff :) I'll get on it at some point soon. Thanks!

**Comment by anandrajeswaran** [comment]
@dalemyers thanks! Look forward to getting some of the excellent guidelines there incorporated! 

Any form of contribution to help get us there would be super welcome, but if it's possible to do so in a series of smaller PRs rather than 1 large one that would be even more welcome :).

**Comment by markavitale** [comment]
@dalemyers I was thinking taking a stab at picking a few of the Outlook conventions and trying to adapt them to this repo's format. The URL you posted doesn't seem to resolve for me anymore. Have they moved?

**Comment by dalemyers** [comment]
We were asked to move it to 1eswiki. However, since it was our own style guide, it wasn't suitable for moving. The goal was to contribute it here, but time requirements got in the way. The repo hosting the content is still up though: https://office.visualstudio.com/Outlook%20Mobile/_git/ios-documentation?path=%2Fsite%2Fcontent%2Fsource_code%2Fstyle_guide%2Fswift
